version: '3'
networks:
  default:

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.back
    container_name: mailer-back
    tty: true
    restart: always
    networks:
      - default
    ports:
      - 8080:8080
    healthcheck:
      test: exit $$( curl -so /dev/null --fail http://127.0.0.1:8080 && echo 0 || echo 1 )
      interval: 30s
      timeout: 1s
      retries: 1
    volumes:
      - ./back/src:/home/api:ro

  scroller:
    build:
      context: ./scroller/
      dockerfile: Dockerfile.scroller
    container_name: mailer-scroller
    tty: true
    restart: always
    networks:
      - default
    volumes:
      - ./scroller/src:/home/api:ro
    environment:
      SMTP_PORT: 465
      SMTP_PASSWORD: 0DjliG9y
      SMTP_USER: eliot@newtechstack.fr
      SMTP_SERVER: smtp.newtechstack.fr

  rethink:
    image: rethinkdb:latest
    container_name: mailer-rethink
    restart: always
    ports:
      - 8081:8080
    expose:
      - 28015
    volumes:
      - ./db/rethink/data:/data
    command: rethinkdb --bind all -d /data
    networks:
      - default
